---
galaxy_info:
  author: Charles Akoto Boadu Jnr
  description: |
    Ansible role to setup rails app
  company: Self
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: Centos
      versions:
        - 7
  categories:
    - system

dependencies: []
