---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Update cache
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Install packages
  apt:
    name: "{{ packages }}"

- name: Move rsyslog service configuration
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/rsyslog.conf

- name: Start syslog service
  systemd:
    name: rsyslog
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Start syslog service
  systemd:
    name: auditd
    state: restarted
    daemon_reload: yes
    enabled: yes
