- name: Create ping workspace
  file:
    path: "{{ user_home }}/go/src/ping"
    state: directory
  register: ping_workspace

- name: Copy code over
  copy:
    src: ping.go
    dest: "{{ ping_workspace.path }}"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Move ping service configuration
  template:
    src: ping.service.j2
    dest: /etc/systemd/system/ping.service

- name: Start ping service
  systemd:
    name: ping
    state: restarted
    daemon_reload: yes
    enabled: yes
