---
- name: Download go
  unarchive:
    src: https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Create go workspace
  file:
    path: "{{ user_home }}/go/src"
    state: directory
