---
- hosts: base
  become: true
  roles:
    - role: base

- hosts: webserver
  become: true
  roles:
    - role: general
    - role: nginx

- hosts: appserver
  become: yes
  roles:
    - role: general
    - role: app

- hosts: logserver
  become: yes
  roles:
    - role: general
    - role: log
