---
- name: Update cache
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Install packages
  apt:
    name: "{{ packages }}"

- name: Create www user
  include_tasks: user.yml
  loop: "{{ users | dict2items }}"