---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Update cache
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
