- name: Create groups
  group:
    name: "{{ item.value.group }}"
    state: present

- name: Enable passwordless sudo for group
  lineinfile:
    path: /etc/sudoers
    regexp: '^%{{ item.value.group }}'
    line: '^%{{ item.value.group }} ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
    state: present

- name: Create user
  user:
    name: "{{ item.key }}"
    comment: "{{ item.value.comment }}"
    uid: "{{ item.value.uid }}"
    group: "{{ item.value.group }}"

- name: Add public key for created user
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ lookup('file', './public_keys/{{ item.key }}.pub') }}"
    state: present

- name: Add sudoers to group
  user:
    name: "{{ item.key }}"
    groups: ["{{ item.value.group }}"]
    append: yes