- name: update yum
  yum:
    name: "*"
    state: latest

- name: setup nginx repo
  yum:
    name: epel-release
    state: latest

- name: install nginx
  yum:
    name: nginx
    enablerepo: "epel"
    state: latest

- name: default nginx configuration reference
  stat: path=/etc/nginx/nginx.conf
  register: default_nginx_conf

- name: rename default nginx configuration if it exists
  command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.disabled
  when: default_nginx_conf.stat.exists

- name: copy over new nginx configuration file
  copy:
    src: ./load-balancer.conf
    dest: /etc/nginx/nginx.conf

- name: enable network http (SELinux configuration)
  command: setsebool -P httpd_can_network_connect 1

- name: start nginx
  systemd:
    name: nginx
    force: yes
    daemon_reload: yes
    enabled: yes
    state: started
