---
- name: Synchronize {{ item }} app directory
  synchronize:
    src: "{{ item }}"
    dest: "{{ apps_dir }}"

- name: Create {{ item }} log directory
  file:
    dest: "{{ log_dir }}/{{ item }}"
    state: directory
    mode: "0755"

- name: Move {{ item }} service configuration
  template:
    src: "{{ item }}.service.j2"
    dest: /etc/systemd/system/{{ item }}.service
    mode: "0755"

- name: Install {{ item }} dependencies
  pip:
    requirements: "{{ apps_dir }}/{{ item }}/requirements.pip"
  when: item == "pythonapp"

- name: Start {{ item }} service
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes