version: ${DW_VERSION:-0.1.0}

server:
  applicationConnectors:
  - type: http 
    port: ${DW_PORT}
  adminConnectors:
  - type: http
    port: ${DW_ADMIN_PORT:-8051}

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: "${DW_LOG_DIR:-./logs}/javaapp.log"
      archive: true
      archivedLogFilenamePattern: "${DW_LOG_DIR:-./logs}/javaapp-%d.log.gz"
      archivedFileCount: 5
      timeZone: UTC
      bufferSize: 8KiB
      immediateFlush: true
    - type: console
      threshold: DEBUG
      target: stdout
      timeZone: UTC